#所有的概率加起来不能超过100，100减去几个概率相加的概率为禁言的概率
#触发语音概率
yugl: 5
#触发文本概率
textgl: 20
#触发图片概率
imggl: 50
#触发反击概率
fjgl: 10
#好感概率（预留项）暂时不影响结果，请勿更改此项
hggl: 0

#网络表情包开关，默认开启（关闭加载本地表情包,表情包位置在qianyu-plugin2/resources/img/表情包文件夹下)
isurlimg: true

#群友戳一戳好感（预留功能，请勿更改）
memberChuoOpen: false

#戳一戳文本
textlist:
  - 不可以戳戳！！！（>~~~<）
  - 好疼！不要戳戳！

#戳一戳语音内容
recordlist:
  - 不可以！！！
  - 达咩！
  - 不要啊！好疼！
